[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.115.0",
    "numpy==1.26.4",
    "pandas==2.2.0",
    "pydantic==2.10.0",
    "python-multipart==0.0.12",
    "requests>=2.32.5",
    "scipy==1.14.0",
    "uvicorn==0.34.0",
]
